### ISSUE TITLE
Modifier for size is around the wrong way

### ISSUE THREAD

**Issue by tardinha** [Firesphere/silverstripe-wysiwyg-font-awesome#1]
When using the size modifier, the icon is rendered as

```<i class="fa fa-bar-chart fa-x4" aria-hidden="true"></i>```

But should be

```<i class="fa fa-bar-chart fa-4x" aria-hidden="true"></i>```

**Comment by Firesphere** [comment]
I've had a bit a break on working on this, but it's resolved on the latest master branch.
